kiali-server:
  auth:
    strategy: anonymous
  
  external_services:
    prometheus:
      url: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
    grafana:
      url: "http://monitoring-grafana.monitoring.svc.cluster.local"
    tracing:
      enabled: true
      in_cluster_url: "http://jaeger-query.jaeger.svc.cluster.local:16686"
      url: "http://jaeger.local"
  
  istio_namespace: "istio-system"
  
  deployment:
    ingress:
      enabled: false
    tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "system"
        effect: "NoSchedule"
