gateway:
  tolerations:
    - key: node-type
      value: system
      effect: NoSchedule
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
